/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.0.2.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as helpers from "../helpers";
import type * as list from "../list";
import type * as lists from "../lists";
import type * as middleware from "../middleware";
import type * as storeUser from "../storeUser";
import type * as sublist from "../sublist";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  helpers: typeof helpers;
  list: typeof list;
  lists: typeof lists;
  middleware: typeof middleware;
  storeUser: typeof storeUser;
  sublist: typeof sublist;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
